### ISSUE TITLE
Questions, BSSID & Default Security

### ISSUE THREAD

**Issue by nevercast** [jczic/MicroWifi#1]
Hello,

This is a great module, thank you for providing this open source. Couple questions:

1. Why are you storing and checking by BSSID, do you have a particular use case where connecting by BSSID instead of using the strongest SSID signal is preferred? Storing the access points by BSSID instead of SSID seems more complicated than it needs to be.

2. Why are you using _DEFAULT_AUTH_TYPE instead of the `sec` property on the Scanned APs?

Thanks!
Josh.

**Comment by jczic** [comment]
Hello and thank you!

1. There is cases with many BSSID for one SSID and an option can store the BSSID directly for more security (just an access point with it MAC address and no a global name).

2. Ah ok :) This is because I wanted to store authentication types for networks but I've not finished that ;)

**Comment by nevercast** [comment]
Thank you very much for your replies.
